USE COMPANY_INVENTORY

BACKUP DATABASE [COMPANY_INVENTORY] TO  
DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CompanyInventoryBackup.bak' WITH INIT, 
NAME = N'COMPANY_INVENTORY-Full Database Backup',
SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO


BACKUP DATABASE COMPANY_INVENTORY TO  
DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CompanyInventoryBackup.bak' 
WITH  DIFFERENTIAL,
NAME = N'COMPANY_INVENTORY-Full Database Backup'
GO

BACKUP LOG COMPANY_INVENTORY TO  
DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CompanyInventoryBackup.bak' 
WITH NOINIT,  NAME = N'COMPANY_INVENTORY-Full Database Backup'
GO