CREATE DATABASE COMPANY_INVENTORY ON  PRIMARY
( NAME = N'COMPANY_DB_FG',
FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\COMPANY_DB_FG.mdf' ,
SIZE = 3072KB , FILEGROWTH = 1024KB ),
FILEGROUP COMPANY_DB_FG_DEFAULT ( NAME = N'COMPANY_DB_FG_DEFAULT',
FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\COMPANY_DB_FG_DEFAULT.ndf' ,
SIZE = 3072KB , FILEGROWTH = 1024KB ),
FILEGROUP COMPANY_DB_FG_INVENTORY ( NAME = N'COMPANY_DB_FG_INVENTORY',
FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\COMPANY_DB_FG_INVENTORY.ndf' ,
SIZE = 3072KB , FILEGROWTH = 1024KB )
LOG ON
( NAME = N'COMPANY_DB_FG_LOG',
FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\COMPANY_DB_FG_LOG.ldf' ,
SIZE = 1024KB , FILEGROWTH = 10%)

USE COMPANY_INVENTORY
GO
ALTER DATABASE COMPANY_INVENTORY MODIFY FILEGROUP COMPANY_DB_FG_INVENTORY DEFAULT
GO
CREATE TABLE PRODUCT(
 PRODUCT_ID INTEGER NOT NULL PRIMARY KEY,
 PART_NUMBER VARCHAR(20) NOT NULL,
 SERIAL_NUMBER VARCHAR(50) NOT NULL,
 PRODUCT_NAME VARCHAR(10) NOT NULL,
 CATEGORY VARCHAR(10) NOT NULL,
 QUANTITY INT NOT NULL DEFAULT 0,
 DATE_ADDED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
)
GO
CREATE TABLE INVENTORY_ORDER(
ORDER_ID VARCHAR(10) PRIMARY KEY,
PRODUCT_ID INTEGER FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
INVOICE_NUMBER VARCHAR(10) NOT NULL,
CUSTOMER_NAME VARCHAR(20) NOT NULL,
TOTAL_QUANTITY INT NOT NULL,
TOTAL_AMOUNT MONEY NOT NULL,
DATE_ORDERED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
)