USE COMPANY_INVENTORY
GO

SELECT PRODUCT_NAME,QUANTITY,
COUNT(*) AS number_of_products
from PRODUCT
GROUP BY PRODUCT_NAME,QUANTITY,PRODUCT_NAME

select 
(select top 1(DATE_ORDERED) 
from INVENTORY_ORDER 
where DATE_ORDERED = '2022-04-03' order by INVOICE_NUMBER Desc) as last_inv ,
(select top 1(DATE_ORDERED) 
from INVENTORY_ORDER
where DATE_ORDERED = '2022-04-03' order by INVOICE_NUMBER Asc) as First_inv


SELECT PRODUCT_NAME,CATEGORY,DATE_ADDED,
COUNT(CATEGORY) AS total_running_product_types from PRODUCT where DATE_ADDED = '2022-04-03'
GROUP BY PRODUCT_NAME,CATEGORY,DATE_ADDED

SELECT PRODUCT_ID, MIN(DATE_ORDERED) as first_tran, MAX(DATE_ORDERED) as last_trans
FROM INVENTORY_ORDER
GROUP BY PRODUCT_ID